### ISSUE TITLE
Majesty repetindo execução de testes

### ISSUE THREAD

**Issue by leonardodelfino** [thrust-bitcodes/majesty#1]
Achamos um cenário que o majesty está duplicando a execução dos testes. Estamos montando nossos testes em vários arquivos separados e então importando todos eles em um arquivo index, para executar todos de uma só vez e dar uma só resposta.

Temos então o seguinte exemplo:

```
let majesty = require('../.lib/bitcodes/thrust-bitcodes/majesty')

var testes1 = function (describe, it, beforeEach, afterEach, expect, should, assert) {
  describe('1. Teste 1', function () {
    it('1.1 - XPTO', function () {
      expect(1).to.equal(1)
    })

    it('1.2 - XPTO', function () {
      expect(1).to.equal(1)
    })
  })
}

var testes2 = function (describe, it, beforeEach, afterEach, expect, should, assert) {
  describe('2. Teste 2', function () {
    it('2.1 - XPTO', function () {
      expect(1).to.equal(1)
    })

    it('2.2 - XPTO', function () {
      expect(1).to.equal(1)
    })
  })
}

majesty.run(testes1)
majesty.run(testes2)
```

Na nossa configuração os arquivos `testes1` e `testes2` são externalizados em novos arquivos, capturamos o resultado desses testes, para então no final gerar o relatório de execução.

Porém temos um problema ao o comando `majesty.run(testes2)` executar, os testes do arquivo `testes1` são executados novamente e printados no log junto com os do arquivo `testes2`.

Segue print do log para melhor entendimento:

![image](https://user-images.githubusercontent.com/1790127/37832780-5d806936-2e88-11e8-9450-d4029305334f.png)

**Comment by cneryjr** [comment]
"Bug" corrigido.
Liberada a versão v0.1.2
